'use client';
import { useState, useTransition } from 'react';
import { browserClient, unwrap } from '../../lib/browser-api';
import type { CommunityChannel } from '../../community/community-feed';

type ManagedChannel = CommunityChannel & { archivedAt?: string | null; position?: number };
export function ChannelManager({ initialChannels }: { initialChannels: ManagedChannel[] }) {
  const [channels, setChannels] = useState(initialChannels); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [readOnly, setReadOnly] = useState(false); const [message, setMessage] = useState(''); const [pending, startTransition] = useTransition();
  function create() { if (name.trim().length < 2) return; startTransition(async () => { try { const result = await browserClient().POST('/api/v1/admin/community/channels', { body: { name: name.trim(), description: description.trim() || undefined, isReadOnly: readOnly, position: channels.length } }); const created = unwrap<ManagedChannel>(result); setChannels((current) => [...current, { ...created, postCount: 0 }]); setName(''); setDescription(''); setReadOnly(false); setMessage('Channel berhasil dibuat.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Channel gagal dibuat.'); } }); }
  function archive(id: string) { startTransition(async () => { try { await browserClient().DELETE('/api/v1/admin/community/channels/{id}', { params: { path: { id } } }); setChannels((current) => current.filter((item) => item.id !== id)); setMessage('Channel diarsipkan.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Channel gagal diarsipkan.'); } }); }
  return <div className="channelManager"><section className="card channelForm"><h2>Buat channel baru</h2><div className="field"><label htmlFor="channel-name">Nama channel</label><input id="channel-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Contoh: Tanya Jawab" /></div><div className="field"><label htmlFor="channel-desc">Keterangan</label><textarea id="channel-desc" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Topik yang dibahas dalam channel ini" /></div><label className="checkRow"><input type="checkbox" checked={readOnly} onChange={(event) => setReadOnly(event.target.checked)} /> Hanya Master yang dapat membuat post</label><button className="btn" type="button" disabled={pending || name.trim().length < 2} onClick={create}>Buat channel</button>{message ? <p role="status" className="communityMessage">{message}</p> : null}</section><section className="channelAdminList"><h2>Channel aktif</h2>{channels.filter((item) => !item.archivedAt).map((item) => <article className="card channelAdminItem" key={item.id}><span className="channelHash">#</span><div><strong>{item.name}</strong><small>{item.description ?? 'Tanpa keterangan'} · {item.postCount} post{item.isReadOnly ? ' · hanya Master' : ''}</small></div><a className="btn secondary" href={`/community/${item.slug}`}>Buka</a><button className="dangerButton" type="button" disabled={pending} onClick={() => archive(item.id)}>Arsipkan</button></article>)}</section></div>;
}
